/**
 * Regenerates public/sitemap.xml.
 *
 * `lastmod` is the date of the last commit that touched the sources behind each
 * route, not the day the file was written: a hand-maintained sitemap drifts the
 * moment someone forgets to bump a date, and a wrong `lastmod` is worse than
 * none — crawlers learn to ignore the whole file.
 *
 * Shared wheels (`/:id`) are deliberately absent: they are user content, and the
 * route serves them `noindex` (see app.routes.ts).
 *
 * Run `npm run sitemap` after adding a route or reworking a page.
 */
import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://www.wheelr.xyz';

/** `sources` are the files whose history dates the page. */
const PAGES = [
  {
    loc: '/',
    changefreq: 'weekly',
    priority: '1.0',
    sources: ['src/index.html', 'src/app/feature/wheel-page'],
    images: [
      {
        loc: `${ORIGIN}/Wheelr.webp`,
        title: 'Wheelr - Free Online Wheel Spinner',
        caption: 'Wheelr is a free wheel for raffles, classrooms, live streams and events',
      },
      { loc: `${ORIGIN}/Logo.webp`, title: 'Wheelr Logo' },
    ],
  },
  { loc: '/templates', changefreq: 'monthly', priority: '0.9', sources: ['src/app/feature/wheel-templates'] },
  { loc: '/info', changefreq: 'monthly', priority: '0.8', sources: ['src/app/feature/info'] },
  { loc: '/donation', changefreq: 'monthly', priority: '0.5', sources: ['src/app/feature/donation'] },
  { loc: '/privacy', changefreq: 'yearly', priority: '0.3', sources: ['src/app/feature/privacy'] },
];

/**
 * Landing-page slugs, read straight out of the source of truth.
 *
 * Importing the TypeScript would need a build step, so the slugs are scraped
 * instead — if the shape of `wheel-templates.seo.ts` ever changes, this throws
 * rather than silently emitting a sitemap that is missing ten pages.
 */
async function templateSlugs() {
  const source = await readFile(join(root, 'src/app/feature/wheel-templates/wheel-templates.seo.ts'), 'utf8');
  const slugs = [...source.matchAll(/^\s{4}slug: '([a-z0-9-]+)',$/gm)].map((match) => match[1]);

  if (!slugs.length) {
    throw new Error('No template slugs found in wheel-templates.seo.ts — has its shape changed?');
  }

  return slugs;
}

/** Last commit date touching any of `paths`, as YYYY-MM-DD. */
function lastModified(paths) {
  const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', ...paths], {
    cwd: root,
    encoding: 'utf8',
  }).trim();

  // A page whose sources are not committed yet has no history to read.
  return out || new Date().toISOString().slice(0, 10);
}

function escapeXml(value) {
  return value.replace(/[<>&'"]/g, (char) => `&${{ '<': 'lt', '>': 'gt', '&': 'amp', "'": 'apos', '"': 'quot' }[char]};`);
}

function imageBlock(image) {
  return [
    '    <image:image>',
    `      <image:loc>${image.loc}</image:loc>`,
    `      <image:title>${escapeXml(image.title)}</image:title>`,
    ...(image.caption ? [`      <image:caption>${escapeXml(image.caption)}</image:caption>`] : []),
    '    </image:image>',
  ].join('\n');
}

const templatePages = (await templateSlugs()).map((slug) => ({
  loc: `/templates/${slug}`,
  changefreq: 'monthly',
  priority: '0.7',
  sources: ['src/app/feature/wheel-templates'],
}));

const body = [...PAGES, ...templatePages].map((page) =>
  [
    '  <url>',
    `    <loc>${ORIGIN}${page.loc}</loc>`,
    `    <lastmod>${lastModified(page.sources)}</lastmod>`,
    `    <changefreq>${page.changefreq}</changefreq>`,
    `    <priority>${page.priority}</priority>`,
    ...(page.images ?? []).map(imageBlock),
    '  </url>',
  ].join('\n')
).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/generate-sitemap.mjs — run \`npm run sitemap\`, do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${body}
</urlset>
`;

await writeFile(join(root, 'public', 'sitemap.xml'), xml, 'utf8');
console.log(`sitemap.xml: ${PAGES.length + templatePages.length} urls (${templatePages.length} template landing pages)`);
