import { WheelTemplateDefinition } from '../../services/wheel-configurator.models';

export interface WheelTemplateItem extends WheelTemplateDefinition {
  id: string;
  emoji: string;
  tagline: string;
}

export const WHEEL_TEMPLATES: WheelTemplateItem[] = [
  {
    id: 'yes-or-no',
    emoji: '✅',
    tagline: $localize`:@@tpl.yes-or-no.tagline:Instant decisions`,
    name: $localize`:@@tpl.yes-or-no.name:Yes or No`,
    description: $localize`:@@tpl.yes-or-no.cardDesc:A quick decision maker: let the wheel answer for you.`,
    names: [$localize`:@@tpl.yes-or-no.entry1:Yes`, $localize`:@@tpl.yes-or-no.entry2:No`, $localize`:@@tpl.yes-or-no.entry1:Yes`, $localize`:@@tpl.yes-or-no.entry2:No`, $localize`:@@tpl.yes-or-no.entry1:Yes`, $localize`:@@tpl.yes-or-no.entry2:No`],
    palette: { name: 'Yes or No', colors: ['#10B981', '#EF4444'] },
    centerText: $localize`:@@tpl.yes-or-no.centerText:PICK`,
    centerColor: '#0f172a',
    winnerEffect: 'confetti',
    pointerType: 'arrow',
    spinDurationMs: 3000,
  },
  {
    id: 'prize-giveaway',
    emoji: '🎁',
    tagline: $localize`:@@tpl.prize-giveaway.tagline:Giveaways & contests`,
    name: $localize`:@@tpl.prize-giveaway.name:Prize Giveaway`,
    description: $localize`:@@tpl.prize-giveaway.cardDesc:A ready-made prize wheel for giveaways, streams, and events.`,
    names: [
      $localize`:@@tpl.prize-giveaway.entry1:€50 Gift Card`,
      $localize`:@@tpl.prize-giveaway.entry2:Free T-Shirt`,
      $localize`:@@tpl.prize-giveaway.entry3:Sticker Pack`,
      $localize`:@@tpl.prize-giveaway.entry4:Mystery Box`,
      $localize`:@@tpl.prize-giveaway.entry5:20% Discount`,
      $localize`:@@tpl.prize-giveaway.entry6:Free Shipping`,
      $localize`:@@tpl.prize-giveaway.entry7:Try Again`,
      $localize`:@@tpl.prize-giveaway.entry8:Grand Prize`,
    ],
    palette: {
      name: 'Prize Gold',
      colors: ['#F59E0B', '#B45309', '#FBBF24', '#78350F', '#FDE68A', '#92400E'],
    },
    centerText: $localize`:@@tpl.prize-giveaway.centerText:WIN`,
    centerColor: '#F59E0B',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 5000,
  },
  {
    id: 'whats-for-dinner',
    emoji: '🍕',
    tagline: $localize`:@@tpl.whats-for-dinner.tagline:Food roulette`,
    name: $localize`:@@tpl.whats-for-dinner.name:What's for Dinner?`,
    description: $localize`:@@tpl.whats-for-dinner.cardDesc:Nobody can decide? Spin and dinner is served.`,
    names: [$localize`:@@tpl.whats-for-dinner.entry1:Pizza`, $localize`:@@tpl.whats-for-dinner.entry2:Sushi`, $localize`:@@tpl.whats-for-dinner.entry3:Burger`, $localize`:@@tpl.whats-for-dinner.entry4:Pasta`, $localize`:@@tpl.whats-for-dinner.entry5:Tacos`, $localize`:@@tpl.whats-for-dinner.entry6:Salad`, $localize`:@@tpl.whats-for-dinner.entry7:Ramen`, $localize`:@@tpl.whats-for-dinner.entry8:BBQ`],
    palette: {
      name: 'Dinner Warm',
      colors: ['#f43f5e', '#fb923c', '#fbbf24', '#84cc16', '#f97316', '#dc2626'],
    },
    centerText: $localize`:@@tpl.whats-for-dinner.centerText:EAT`,
    centerColor: '#fb923c',
    winnerEffect: 'cartoon-fire',
    pointerType: 'drop',
    spinDurationMs: 3000,
  },
  {
    id: 'team-picker',
    emoji: '👥',
    tagline: $localize`:@@tpl.team-picker.tagline:Standups & classrooms`,
    name: $localize`:@@tpl.team-picker.name:Team Picker`,
    description: $localize`:@@tpl.team-picker.cardDesc:Pick who speaks next, who presents, or who buys coffee.`,
    names: ['Alex', 'Sam', 'Charlie', 'Jordan', 'Taylor', 'Riley', 'Morgan', 'Casey'],
    palette: {
      name: 'Team Cool',
      colors: ['#3B82F6', '#06B6D4', '#8B5CF6', '#0EA5E9', '#6366F1', '#14B8A6'],
    },
    centerText: $localize`:@@tpl.team-picker.centerText:PICK`,
    centerColor: '#3B82F6',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3000,
  },
  {
    id: 'truth-or-dare',
    emoji: '🎭',
    tagline: $localize`:@@tpl.truth-or-dare.tagline:Party games`,
    name: $localize`:@@tpl.truth-or-dare.name:Truth or Dare`,
    description: $localize`:@@tpl.truth-or-dare.cardDesc:The party classic: let the wheel raise the stakes.`,
    names: [$localize`:@@tpl.truth-or-dare.entry1:Truth`, $localize`:@@tpl.truth-or-dare.entry2:Dare`, $localize`:@@tpl.truth-or-dare.entry1:Truth`, $localize`:@@tpl.truth-or-dare.entry2:Dare`, $localize`:@@tpl.truth-or-dare.entry1:Truth`, $localize`:@@tpl.truth-or-dare.entry2:Dare`, $localize`:@@tpl.truth-or-dare.entry1:Truth`, $localize`:@@tpl.truth-or-dare.entry2:Dare`],
    palette: { name: 'Truth or Dare', colors: ['#A855F7', '#EC4899'] },
    centerText: $localize`:@@tpl.truth-or-dare.centerText:DARE`,
    centerColor: '#A855F7',
    winnerEffect: 'confetti',
    pointerType: 'bolt',
    spinDurationMs: 3000,
  },
  {
    id: 'discount-wheel',
    emoji: '🏷️',
    tagline: $localize`:@@tpl.discount-wheel.tagline:Shops & promos`,
    name: $localize`:@@tpl.discount-wheel.name:Discount Wheel`,
    description: $localize`:@@tpl.discount-wheel.cardDesc:Spin-to-win promo wheel for shops, fairs, and landing pages.`,
    names: [
      $localize`:@@tpl.discount-wheel.entry1:5% Off`,
      $localize`:@@tpl.discount-wheel.entry2:10% Off`,
      $localize`:@@tpl.discount-wheel.entry3:15% Off`,
      $localize`:@@tpl.discount-wheel.entry4:20% Off`,
      $localize`:@@tpl.discount-wheel.entry5:30% Off`,
      $localize`:@@tpl.discount-wheel.entry6:50% Off`,
      $localize`:@@tpl.discount-wheel.entry7:Free Gift`,
      $localize`:@@tpl.discount-wheel.entry8:No Luck`,
    ],
    palette: {
      name: 'Promo Pop',
      colors: ['#EF4444', '#F59E0B', '#10B981', '#3B82F6', '#A855F7', '#EC4899'],
    },
    centerText: $localize`:@@tpl.discount-wheel.centerText:SPIN`,
    centerColor: '#EF4444',
    winnerEffect: 'fireworks',
    pointerType: 'diamond',
    spinDurationMs: 4000,
  },
  {
    id: 'movie-night',
    emoji: '🎬',
    tagline: $localize`:@@tpl.movie-night.tagline:Movie night`,
    name: $localize`:@@tpl.movie-night.name:Movie Night`,
    description: $localize`:@@tpl.movie-night.cardDesc:Pick tonight’s genre and stop scrolling the catalog.`,
    names: [
      $localize`:@@tpl.movie-night.entry1:Action`,
      $localize`:@@tpl.movie-night.entry2:Comedy`,
      $localize`:@@tpl.movie-night.entry3:Horror`,
      $localize`:@@tpl.movie-night.entry4:Sci-Fi`,
      $localize`:@@tpl.movie-night.entry5:Romance`,
      $localize`:@@tpl.movie-night.entry6:Thriller`,
      $localize`:@@tpl.movie-night.entry7:Animation`,
      $localize`:@@tpl.movie-night.entry8:Documentary`,
    ],
    palette: {
      name: 'Cinema Noir',
      colors: ['#0f172a', '#7c3aed', '#1e293b', '#f43f5e', '#334155', '#f59e0b'],
    },
    centerText: $localize`:@@tpl.movie-night.centerText:PLAY`,
    centerColor: '#7c3aed',
    winnerEffect: 'confetti',
    pointerType: 'drop',
    spinDurationMs: 3000,
  },
  {
    id: 'workout-spinner',
    emoji: '💪',
    tagline: $localize`:@@tpl.workout-spinner.tagline:Fitness`,
    name: $localize`:@@tpl.workout-spinner.name:Workout Spinner`,
    description: $localize`:@@tpl.workout-spinner.cardDesc:Random mini-workouts: spin and do what the wheel says.`,
    names: [
      $localize`:@@tpl.workout-spinner.entry1:10 Push-ups`,
      $localize`:@@tpl.workout-spinner.entry2:20 Squats`,
      $localize`:@@tpl.workout-spinner.entry3:30s Plank`,
      $localize`:@@tpl.workout-spinner.entry4:15 Burpees`,
      $localize`:@@tpl.workout-spinner.entry5:20 Jumping Jacks`,
      $localize`:@@tpl.workout-spinner.entry6:10 Lunges`,
      $localize`:@@tpl.workout-spinner.entry7:30s Wall Sit`,
      $localize`:@@tpl.workout-spinner.entry8:Rest 1 min`,
    ],
    palette: {
      name: 'Energy',
      colors: ['#22c55e', '#16a34a', '#84cc16', '#15803d', '#a3e635', '#4d7c0f'],
    },
    centerText: $localize`:@@tpl.workout-spinner.centerText:GO!`,
    centerColor: '#22c55e',
    winnerEffect: 'fire',
    pointerType: 'bolt',
    spinDurationMs: 3000,
  },
  {
    id: 'lucky-numbers',
    emoji: '🎱',
    tagline: $localize`:@@tpl.lucky-numbers.tagline:Raffles & lotteries`,
    name: $localize`:@@tpl.lucky-numbers.name:Lucky Numbers`,
    description: $localize`:@@tpl.lucky-numbers.cardDesc:Numbers 1 to 12 for raffles, tombola, and quick draws.`,
    names: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    palette: {
      name: 'Neon Numbers',
      colors: ['#39FF14', '#FF00FF', '#00FFFF', '#FFFF00', '#FF5F1F', '#4D4DFF'],
    },
    centerText: $localize`:@@tpl.lucky-numbers.centerText:LUCK`,
    centerColor: '#00FFFF',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 5000,
  },
  {
    id: 'icebreaker-questions',
    emoji: '🧊',
    tagline: $localize`:@@tpl.icebreaker-questions.tagline:Meetings & meetups`,
    name: $localize`:@@tpl.icebreaker-questions.name:Icebreaker Questions`,
    description: $localize`:@@tpl.icebreaker-questions.cardDesc:Warm up any group: spin for a random get-to-know-you question.`,
    names: [
      $localize`:@@tpl.icebreaker-questions.entry1:Dream vacation?`,
      $localize`:@@tpl.icebreaker-questions.entry2:Hidden talent?`,
      $localize`:@@tpl.icebreaker-questions.entry3:Favorite food?`,
      $localize`:@@tpl.icebreaker-questions.entry4:Best concert ever?`,
      $localize`:@@tpl.icebreaker-questions.entry5:Pick a superpower`,
      $localize`:@@tpl.icebreaker-questions.entry6:First job story`,
      $localize`:@@tpl.icebreaker-questions.entry7:Karaoke go-to song`,
      $localize`:@@tpl.icebreaker-questions.entry8:Weirdest habit?`,
    ],
    palette: {
      name: 'Icebreaker',
      colors: ['#0891b2', '#38bdf8', '#0e7490', '#7dd3fc', '#0369a1', '#bae6fd'],
    },
    centerText: $localize`:@@tpl.icebreaker-questions.centerText:ASK`,
    centerColor: '#38bdf8',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3000,
  },
  {
    id: 'random-name-picker',
    emoji: '🎓',
    tagline: $localize`:@@tpl.random-name-picker.tagline:Classrooms & calls`,
    name: $localize`:@@tpl.random-name-picker.name:Random Name Picker`,
    description: $localize`:@@tpl.random-name-picker.cardDesc:Pick a name at random when every hand is down — or every hand is up.`,
    names: ['Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Ethan', 'Sophia', 'Mason', 'Isabella', 'Lucas'],
    palette: {
      name: 'Classroom',
      colors: ['#2563eb', '#f59e0b', '#16a34a', '#db2777', '#7c3aed', '#0891b2'],
    },
    centerText: $localize`:@@tpl.random-name-picker.centerText:PICK`,
    centerColor: '#2563eb',
    winnerEffect: 'confetti',
    pointerType: 'finger',
    spinDurationMs: 3000,
  },
  {
    id: 'would-you-rather',
    emoji: '🤔',
    tagline: $localize`:@@tpl.would-you-rather.tagline:Party questions`,
    name: $localize`:@@tpl.would-you-rather.name:Would You Rather`,
    description: $localize`:@@tpl.would-you-rather.cardDesc:Impossible choices, chosen for you. Spin and defend your answer.`,
    names: [
      $localize`:@@tpl.would-you-rather.entry1:Fly or be invisible?`,
      $localize`:@@tpl.would-you-rather.entry2:Past or future?`,
      $localize`:@@tpl.would-you-rather.entry3:No music or no films?`,
      $localize`:@@tpl.would-you-rather.entry4:Always hot or always cold?`,
      $localize`:@@tpl.would-you-rather.entry5:Read minds or teleport?`,
      $localize`:@@tpl.would-you-rather.entry6:Rich or famous?`,
      $localize`:@@tpl.would-you-rather.entry7:No internet or no phone?`,
      $localize`:@@tpl.would-you-rather.entry8:Never sleep or never eat?`,
    ],
    palette: {
      name: 'Dilemma',
      colors: ['#6366f1', '#ec4899', '#8b5cf6', '#f43f5e', '#3b82f6', '#d946ef'],
    },
    centerText: $localize`:@@tpl.would-you-rather.centerText:PICK`,
    centerColor: '#8b5cf6',
    winnerEffect: 'confetti',
    pointerType: 'diamond',
    spinDurationMs: 3500,
  },
  {
    id: 'never-have-i-ever',
    emoji: '🙊',
    tagline: $localize`:@@tpl.never-have-i-ever.tagline:Game night`,
    name: $localize`:@@tpl.never-have-i-ever.name:Never Have I Ever`,
    description: $localize`:@@tpl.never-have-i-ever.cardDesc:The classic confession game, with the wheel choosing the prompt.`,
    names: [
      $localize`:@@tpl.never-have-i-ever.entry1:Sung karaoke sober`,
      $localize`:@@tpl.never-have-i-ever.entry2:Missed a flight`,
      $localize`:@@tpl.never-have-i-ever.entry3:Faked knowing a song`,
      $localize`:@@tpl.never-have-i-ever.entry4:Talked in my sleep`,
      $localize`:@@tpl.never-have-i-ever.entry5:Ghosted a group chat`,
      $localize`:@@tpl.never-have-i-ever.entry6:Cried at an advert`,
      $localize`:@@tpl.never-have-i-ever.entry7:Got lost in my own town`,
      $localize`:@@tpl.never-have-i-ever.entry8:Texted the wrong person`,
    ],
    palette: {
      name: 'Confession',
      colors: ['#f97316', '#ef4444', '#facc15', '#fb7185', '#f59e0b', '#e11d48'],
    },
    centerText: $localize`:@@tpl.never-have-i-ever.centerText:SPILL`,
    centerColor: '#f97316',
    winnerEffect: 'confetti',
    pointerType: 'star',
    spinDurationMs: 3500,
  },
  {
    id: 'chore-wheel',
    emoji: '🧹',
    tagline: $localize`:@@tpl.chore-wheel.tagline:Housemates & family`,
    name: $localize`:@@tpl.chore-wheel.name:Chore Wheel`,
    description: $localize`:@@tpl.chore-wheel.cardDesc:Who does what this week, decided by something nobody can argue with.`,
    names: [
      $localize`:@@tpl.chore-wheel.entry1:Dishes`,
      $localize`:@@tpl.chore-wheel.entry2:Bins out`,
      $localize`:@@tpl.chore-wheel.entry3:Bathroom`,
      $localize`:@@tpl.chore-wheel.entry4:Hoovering`,
      $localize`:@@tpl.chore-wheel.entry5:Laundry`,
      $localize`:@@tpl.chore-wheel.entry6:Cooking`,
      $localize`:@@tpl.chore-wheel.entry7:Food shop`,
      $localize`:@@tpl.chore-wheel.entry8:Day off`,
    ],
    palette: {
      name: 'Household',
      colors: ['#0d9488', '#65a30d', '#0891b2', '#84cc16', '#14b8a6', '#4d7c0f'],
    },
    centerText: $localize`:@@tpl.chore-wheel.centerText:CHORE`,
    centerColor: '#0d9488',
    winnerEffect: 'applause',
    pointerType: 'arrow',
    spinDurationMs: 3000,
  },
  {
    id: 'secret-santa',
    emoji: '🎅',
    tagline: $localize`:@@tpl.secret-santa.tagline:Gift exchanges`,
    name: $localize`:@@tpl.secret-santa.name:Secret Santa`,
    description: $localize`:@@tpl.secret-santa.cardDesc:Draw names for a gift exchange in front of everyone, no hat required.`,
    names: ['Anna', 'Ben', 'Chiara', 'David', 'Elena', 'Marco', 'Nina', 'Paul'],
    palette: {
      name: 'Festive',
      colors: ['#dc2626', '#15803d', '#f8fafc', '#b91c1c', '#166534', '#fbbf24'],
    },
    centerText: $localize`:@@tpl.secret-santa.centerText:DRAW`,
    centerColor: '#dc2626',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 4000,
  },
  {
    id: 'random-letter',
    emoji: '🔤',
    tagline: $localize`:@@tpl.random-letter.tagline:Word games & class`,
    name: $localize`:@@tpl.random-letter.name:Random Letter`,
    description: $localize`:@@tpl.random-letter.cardDesc:A to Z on one wheel: spin for a letter and start the round.`,
    names: [
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
      'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    ],
    palette: {
      name: 'Alphabet',
      colors: ['#1d4ed8', '#7c3aed', '#0891b2', '#c026d3', '#2563eb', '#9333ea'],
    },
    centerText: $localize`:@@tpl.random-letter.centerText:A-Z`,
    centerColor: '#1d4ed8',
    winnerEffect: 'confetti',
    pointerType: 'arrow',
    spinDurationMs: 3000,
  },
  {
    id: 'random-country',
    emoji: '🌍',
    tagline: $localize`:@@tpl.random-country.tagline:Geography & quizzes`,
    name: $localize`:@@tpl.random-country.name:Random Country`,
    description: $localize`:@@tpl.random-country.cardDesc:Spin the globe without the globe: a random country every time.`,
    names: [
      $localize`:@@tpl.random-country.entry1:Japan`, $localize`:@@tpl.random-country.entry2:Brazil`, $localize`:@@tpl.random-country.entry3:Italy`, $localize`:@@tpl.random-country.entry4:Kenya`, $localize`:@@tpl.random-country.entry5:Canada`, $localize`:@@tpl.random-country.entry6:India`,
      $localize`:@@tpl.random-country.entry7:Norway`, $localize`:@@tpl.random-country.entry8:Mexico`, $localize`:@@tpl.random-country.entry9:Australia`, $localize`:@@tpl.random-country.entry10:Portugal`, $localize`:@@tpl.random-country.entry11:Vietnam`, $localize`:@@tpl.random-country.entry12:Morocco`,
    ],
    palette: {
      name: 'Atlas',
      colors: ['#0e7490', '#15803d', '#b45309', '#1e40af', '#047857', '#c2410c'],
    },
    centerText: $localize`:@@tpl.random-country.centerText:GO`,
    centerColor: '#0e7490',
    winnerEffect: 'confetti',
    pointerType: 'drop',
    spinDurationMs: 3500,
  },
  {
    id: 'random-animal',
    emoji: '🦊',
    tagline: $localize`:@@tpl.random-animal.tagline:Kids & classrooms`,
    name: $localize`:@@tpl.random-animal.name:Random Animal`,
    description: $localize`:@@tpl.random-animal.cardDesc:Spin for an animal: charades, drawing games and quiet-time prompts.`,
    names: [
      $localize`:@@tpl.random-animal.entry1:Fox`, $localize`:@@tpl.random-animal.entry2:Elephant`, $localize`:@@tpl.random-animal.entry3:Penguin`, $localize`:@@tpl.random-animal.entry4:Tiger`, $localize`:@@tpl.random-animal.entry5:Octopus`, $localize`:@@tpl.random-animal.entry6:Owl`,
      $localize`:@@tpl.random-animal.entry7:Kangaroo`, $localize`:@@tpl.random-animal.entry8:Dolphin`, $localize`:@@tpl.random-animal.entry9:Panda`, $localize`:@@tpl.random-animal.entry10:Crocodile`,
    ],
    palette: {
      name: 'Safari',
      colors: ['#ea580c', '#65a30d', '#0891b2', '#a16207', '#16a34a', '#d97706'],
    },
    centerText: $localize`:@@tpl.random-animal.centerText:WILD`,
    centerColor: '#ea580c',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3000,
  },
  {
    id: 'date-night',
    emoji: '💘',
    tagline: $localize`:@@tpl.date-night.tagline:Couples`,
    name: $localize`:@@tpl.date-night.name:Date Night Ideas`,
    description: $localize`:@@tpl.date-night.cardDesc:Neither of you can decide? The wheel plans the evening.`,
    names: [
      $localize`:@@tpl.date-night.entry1:Cook something new`,
      $localize`:@@tpl.date-night.entry2:Cinema`,
      $localize`:@@tpl.date-night.entry3:Long walk`,
      $localize`:@@tpl.date-night.entry4:Board games`,
      $localize`:@@tpl.date-night.entry5:Try a new bar`,
      $localize`:@@tpl.date-night.entry6:Picnic`,
      $localize`:@@tpl.date-night.entry7:Live music`,
      $localize`:@@tpl.date-night.entry8:Stay in, no phones`,
    ],
    palette: {
      name: 'Date Night',
      colors: ['#e11d48', '#f43f5e', '#be123c', '#fb7185', '#9f1239', '#fda4af'],
    },
    centerText: $localize`:@@tpl.date-night.centerText:TONIGHT`,
    centerColor: '#e11d48',
    winnerEffect: 'confetti',
    pointerType: 'drop',
    spinDurationMs: 3500,
  },
  {
    id: 'where-to-travel',
    emoji: '✈️',
    tagline: $localize`:@@tpl.where-to-travel.tagline:Trips & weekends`,
    name: $localize`:@@tpl.where-to-travel.name:Where to Travel`,
    description: $localize`:@@tpl.where-to-travel.cardDesc:Put the shortlist on the wheel and let it settle the argument.`,
    names: [
      $localize`:@@tpl.where-to-travel.entry1:Lisbon`, $localize`:@@tpl.where-to-travel.entry2:Reykjavik`, $localize`:@@tpl.where-to-travel.entry3:Athens`, $localize`:@@tpl.where-to-travel.entry4:Edinburgh`, $localize`:@@tpl.where-to-travel.entry5:Marrakesh`,
      $localize`:@@tpl.where-to-travel.entry6:Vienna`, $localize`:@@tpl.where-to-travel.entry7:Copenhagen`, $localize`:@@tpl.where-to-travel.entry8:Seville`, $localize`:@@tpl.where-to-travel.entry9:Prague`, $localize`:@@tpl.where-to-travel.entry10:Split`,
    ],
    palette: {
      name: 'Departures',
      colors: ['#0284c7', '#0ea5e9', '#0369a1', '#38bdf8', '#075985', '#7dd3fc'],
    },
    centerText: $localize`:@@tpl.where-to-travel.centerText:FLY`,
    centerColor: '#0284c7',
    winnerEffect: 'fireworks',
    pointerType: 'bolt',
    spinDurationMs: 4000,
  },
  {
    id: 'instagram-giveaway',
    emoji: '📣',
    tagline: $localize`:@@tpl.instagram-giveaway.tagline:Social giveaways`,
    name: $localize`:@@tpl.instagram-giveaway.name:Instagram Giveaway Picker`,
    description: $localize`:@@tpl.instagram-giveaway.cardDesc:Paste the usernames from the comments and spin for a winner on camera.`,
    // Usernames are placeholders the user replaces; they stay untranslated.
    names: ['@anna.designs', '@marco_runs', '@the.plant.lady', '@luca.eats', '@sara_travels', '@gamer.tom', '@julia.reads', '@dan.makes'],
    palette: {
      name: 'Gradient Pop',
      colors: ['#f58529', '#dd2a7b', '#8134af', '#515bd4', '#feda77', '#c13584'],
    },
    centerText: $localize`:@@tpl.instagram-giveaway.centerText:WIN`,
    centerColor: '#dd2a7b',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 6000,
  },
  {
    id: 'who-pays',
    emoji: '💸',
    tagline: $localize`:@@tpl.who-pays.tagline:Coffee, lunch & the bill`,
    name: $localize`:@@tpl.who-pays.name:Who Pays?`,
    description: $localize`:@@tpl.who-pays.cardDesc:Coffee round, dinner bill, next pizza: the wheel picks who is paying.`,
    names: ['Alex', 'Sam', 'Jordan', 'Taylor', 'Morgan', 'Riley'],
    palette: {
      name: 'Receipt',
      colors: ['#16a34a', '#0f766e', '#22c55e', '#166534', '#10b981', '#065f46'],
    },
    centerText: $localize`:@@tpl.who-pays.centerText:PAY`,
    centerColor: '#16a34a',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 4000,
  },
  {
    id: 'classroom-rewards',
    emoji: '🏅',
    tagline: $localize`:@@tpl.classroom-rewards.tagline:Teachers & classrooms`,
    name: $localize`:@@tpl.classroom-rewards.name:Classroom Reward Wheel`,
    description: $localize`:@@tpl.classroom-rewards.cardDesc:Rewards that cost nothing, picked by a spin the whole class watches.`,
    names: [
      $localize`:@@tpl.classroom-rewards.entry1:Homework pass`,
      $localize`:@@tpl.classroom-rewards.entry2:Pick your seat`,
      $localize`:@@tpl.classroom-rewards.entry3:Class DJ`,
      $localize`:@@tpl.classroom-rewards.entry4:Extra break time`,
      $localize`:@@tpl.classroom-rewards.entry5:Teacher's helper`,
      $localize`:@@tpl.classroom-rewards.entry6:Sticker`,
      $localize`:@@tpl.classroom-rewards.entry7:Pick the class game`,
      $localize`:@@tpl.classroom-rewards.entry8:Teacher’s desk`,
    ],
    palette: {
      name: 'Gold Stars',
      colors: ['#f59e0b', '#2563eb', '#16a34a', '#db2777', '#7c3aed', '#ea580c'],
    },
    centerText: $localize`:@@tpl.classroom-rewards.centerText:STAR`,
    centerColor: '#f59e0b',
    winnerEffect: 'confetti',
    pointerType: 'star',
    spinDurationMs: 3500,
  },
  {
    id: 'fantasy-draft',
    emoji: '🏈',
    tagline: $localize`:@@tpl.fantasy-draft.tagline:Fantasy leagues`,
    name: $localize`:@@tpl.fantasy-draft.name:Fantasy Draft Order`,
    description: $localize`:@@tpl.fantasy-draft.cardDesc:Settle your league's draft order live, in front of every manager.`,
    names: [
      $localize`:@@tpl.fantasy-draft.entry1:Team 1`, $localize`:@@tpl.fantasy-draft.entry2:Team 2`, $localize`:@@tpl.fantasy-draft.entry3:Team 3`, $localize`:@@tpl.fantasy-draft.entry4:Team 4`, $localize`:@@tpl.fantasy-draft.entry5:Team 5`,
      $localize`:@@tpl.fantasy-draft.entry6:Team 6`, $localize`:@@tpl.fantasy-draft.entry7:Team 7`, $localize`:@@tpl.fantasy-draft.entry8:Team 8`, $localize`:@@tpl.fantasy-draft.entry9:Team 9`, $localize`:@@tpl.fantasy-draft.entry10:Team 10`,
    ],
    palette: {
      name: 'Stadium',
      colors: ['#065f46', '#b91c1c', '#1d4ed8', '#ca8a04', '#7c3aed', '#0f766e'],
    },
    centerText: $localize`:@@tpl.fantasy-draft.centerText:DRAFT`,
    centerColor: '#065f46',
    winnerEffect: 'fireworks',
    pointerType: 'arrow',
    spinDurationMs: 4500,
  },
  {
    id: 'random-color',
    emoji: '🎨',
    tagline: $localize`:@@tpl.random-color.tagline:Art & games`,
    name: $localize`:@@tpl.random-color.name:Random Color Wheel`,
    description: $localize`:@@tpl.random-color.cardDesc:Spin for a color: art challenges, outfits, party themes and games.`,
    names: [
      $localize`:@@tpl.random-color.entry1:Red`, $localize`:@@tpl.random-color.entry2:Orange`, $localize`:@@tpl.random-color.entry3:Yellow`, $localize`:@@tpl.random-color.entry4:Green`, $localize`:@@tpl.random-color.entry5:Teal`,
      $localize`:@@tpl.random-color.entry6:Blue`, $localize`:@@tpl.random-color.entry7:Purple`, $localize`:@@tpl.random-color.entry8:Pink`, $localize`:@@tpl.random-color.entry9:Brown`, $localize`:@@tpl.random-color.entry10:Black`,
    ],
    palette: {
      // One colour per entry, in the same order, so every slice is painted in the colour it names.
      name: 'Colour Names',
      colors: ['#ef4444', '#f97316', '#facc15', '#22c55e', '#14b8a6', '#3b82f6', '#a855f7', '#ec4899', '#92400e', '#171717'],
    },
    centerText: $localize`:@@tpl.random-color.centerText:COLOR`,
    centerColor: '#ffffff',
    winnerEffect: 'confetti',
    pointerType: 'diamond',
    spinDurationMs: 3500,
  },
  {
    id: 'what-to-draw',
    emoji: '✏️',
    tagline: $localize`:@@tpl.what-to-draw.tagline:Sketchbook prompts`,
    name: $localize`:@@tpl.what-to-draw.name:What to Draw`,
    description: $localize`:@@tpl.what-to-draw.cardDesc:Blank page? Spin for something to draw and start sketching.`,
    names: [
      $localize`:@@tpl.what-to-draw.entry1:A dragon`, $localize`:@@tpl.what-to-draw.entry2:A lighthouse`, $localize`:@@tpl.what-to-draw.entry3:A robot`, $localize`:@@tpl.what-to-draw.entry4:A treehouse`, $localize`:@@tpl.what-to-draw.entry5:An octopus`,
      $localize`:@@tpl.what-to-draw.entry6:A castle`, $localize`:@@tpl.what-to-draw.entry7:A cat in a hat`, $localize`:@@tpl.what-to-draw.entry8:A spaceship`, $localize`:@@tpl.what-to-draw.entry9:A haunted house`, $localize`:@@tpl.what-to-draw.entry10:Your favourite snack`,
    ],
    palette: {
      name: 'Sketchbook',
      colors: ['#0f172a', '#334155', '#1e3a8a', '#475569', '#0e7490', '#64748b'],
    },
    centerText: $localize`:@@tpl.what-to-draw.centerText:DRAW`,
    centerColor: '#f8fafc',
    winnerEffect: 'cartoon-fire',
    pointerType: 'drop',
    spinDurationMs: 3000,
  },
  {
    id: 'spin-the-bottle',
    emoji: '🍾',
    tagline: $localize`:@@tpl.spin-the-bottle.tagline:Party classic`,
    name: $localize`:@@tpl.spin-the-bottle.name:Spin the Bottle`,
    description: $localize`:@@tpl.spin-the-bottle.cardDesc:The party classic without the bottle: put the players on the wheel and spin.`,
    names: ['Alex', 'Bea', 'Carlos', 'Dani', 'Emma', 'Finn'],
    palette: {
      name: 'Bottle Green',
      colors: ['#166534', '#15803d', '#14532d', '#22c55e', '#065f46', '#4ade80'],
    },
    centerText: $localize`:@@tpl.spin-the-bottle.centerText:SPIN`,
    centerColor: '#166534',
    winnerEffect: 'confetti',
    pointerType: 'arrow',
    spinDurationMs: 4000,
  },
  {
    id: 'zodiac-sign',
    emoji: '♈',
    tagline: $localize`:@@tpl.zodiac-sign.tagline:Astrology & games`,
    name: $localize`:@@tpl.zodiac-sign.name:Random Zodiac Sign`,
    description: $localize`:@@tpl.zodiac-sign.cardDesc:Twelve signs, one spin: a random star sign for games, stories and quizzes.`,
    names: [
      $localize`:@@tpl.zodiac-sign.entry1:Aries`, $localize`:@@tpl.zodiac-sign.entry2:Taurus`, $localize`:@@tpl.zodiac-sign.entry3:Gemini`, $localize`:@@tpl.zodiac-sign.entry4:Cancer`,
      $localize`:@@tpl.zodiac-sign.entry5:Leo`, $localize`:@@tpl.zodiac-sign.entry6:Virgo`, $localize`:@@tpl.zodiac-sign.entry7:Libra`, $localize`:@@tpl.zodiac-sign.entry8:Scorpio`,
      $localize`:@@tpl.zodiac-sign.entry9:Sagittarius`, $localize`:@@tpl.zodiac-sign.entry10:Capricorn`, $localize`:@@tpl.zodiac-sign.entry11:Aquarius`, $localize`:@@tpl.zodiac-sign.entry12:Pisces`,
    ],
    palette: {
      name: 'Night Sky',
      colors: ['#1e1b4b', '#312e81', '#4c1d95', '#1e3a8a', '#581c87', '#3730a3'],
    },
    centerText: $localize`:@@tpl.zodiac-sign.centerText:STARS`,
    centerColor: '#fbbf24',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 4500,
  },
  {
    id: 'baby-names',
    emoji: '👶',
    tagline: $localize`:@@tpl.baby-names.tagline:Expecting parents`,
    name: $localize`:@@tpl.baby-names.name:Baby Name Picker`,
    description: $localize`:@@tpl.baby-names.cardDesc:Put your shortlist of baby names on the wheel and see which one feels right.`,
    names: ['Mia', 'Leo', 'Aria', 'Noah', 'Sofia', 'Luca', 'Zoe', 'Elio', 'Nora', 'Theo'],
    palette: {
      name: 'Nursery',
      colors: ['#f9a8d4', '#93c5fd', '#fde68a', '#a7f3d0', '#c4b5fd', '#fdba74'],
    },
    centerText: $localize`:@@tpl.baby-names.centerText:NAME`,
    centerColor: '#f9a8d4',
    winnerEffect: 'confetti',
    pointerType: 'drop',
    spinDurationMs: 4000,
  },
  {
    id: 'pet-names',
    emoji: '🐾',
    tagline: $localize`:@@tpl.pet-names.tagline:New puppy or kitten`,
    name: $localize`:@@tpl.pet-names.name:Pet Name Picker`,
    description: $localize`:@@tpl.pet-names.cardDesc:A new puppy, kitten or bunny and no name yet? Let the wheel decide.`,
    names: ['Luna', 'Milo', 'Bella', 'Oliver', 'Coco', 'Leo', 'Daisy', 'Max', 'Nala', 'Rocky'],
    palette: {
      name: 'Paw Prints',
      colors: ['#b45309', '#d97706', '#78350f', '#f59e0b', '#92400e', '#fbbf24'],
    },
    centerText: $localize`:@@tpl.pet-names.centerText:PET`,
    centerColor: '#b45309',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3500,
  },
  {
    id: 'party-games',
    emoji: '🎉',
    tagline: $localize`:@@tpl.party-games.tagline:Birthdays & parties`,
    name: $localize`:@@tpl.party-games.name:Party Games`,
    description: $localize`:@@tpl.party-games.cardDesc:Which game next? Spin and keep the party moving.`,
    names: [
      $localize`:@@tpl.party-games.entry1:Charades`, $localize`:@@tpl.party-games.entry2:Musical chairs`, $localize`:@@tpl.party-games.entry3:Two truths and a lie`, $localize`:@@tpl.party-games.entry4:Karaoke round`,
      $localize`:@@tpl.party-games.entry5:Limbo`, $localize`:@@tpl.party-games.entry6:Hot potato`, $localize`:@@tpl.party-games.entry7:Treasure hunt`, $localize`:@@tpl.party-games.entry8:Freeze dance`,
    ],
    palette: {
      name: 'Balloons',
      colors: ['#ef4444', '#3b82f6', '#eab308', '#22c55e', '#a855f7', '#f97316'],
    },
    centerText: $localize`:@@tpl.party-games.centerText:PLAY`,
    centerColor: '#ef4444',
    winnerEffect: 'confetti',
    pointerType: 'star',
    spinDurationMs: 3500,
  },
  {
    id: 'study-subject',
    emoji: '📚',
    tagline: $localize`:@@tpl.study-subject.tagline:Revision & homework`,
    name: $localize`:@@tpl.study-subject.name:What to Study`,
    description: $localize`:@@tpl.study-subject.cardDesc:Can’t choose where to start revising? Spin for the next subject.`,
    names: [
      $localize`:@@tpl.study-subject.entry1:Maths`, $localize`:@@tpl.study-subject.entry2:History`, $localize`:@@tpl.study-subject.entry3:Science`, $localize`:@@tpl.study-subject.entry4:Languages`,
      $localize`:@@tpl.study-subject.entry5:Geography`, $localize`:@@tpl.study-subject.entry6:Literature`, $localize`:@@tpl.study-subject.entry7:Art`, $localize`:@@tpl.study-subject.entry8:Quick quiz`,
    ],
    palette: {
      name: 'Library',
      colors: ['#1d4ed8', '#0f766e', '#7c2d12', '#4338ca', '#15803d', '#9f1239'],
    },
    centerText: $localize`:@@tpl.study-subject.centerText:STUDY`,
    centerColor: '#1d4ed8',
    winnerEffect: 'applause',
    pointerType: 'arrow',
    spinDurationMs: 3000,
  },
  {
    id: 'random-hobby',
    emoji: '🧶',
    tagline: $localize`:@@tpl.random-hobby.tagline:Try something new`,
    name: $localize`:@@tpl.random-hobby.name:Random Hobby`,
    description: $localize`:@@tpl.random-hobby.cardDesc:Looking for a new hobby? Spin and give the first one a real try.`,
    names: [
      $localize`:@@tpl.random-hobby.entry1:Baking`, $localize`:@@tpl.random-hobby.entry2:Gardening`, $localize`:@@tpl.random-hobby.entry3:Chess`, $localize`:@@tpl.random-hobby.entry4:Photography`,
      $localize`:@@tpl.random-hobby.entry5:Knitting`, $localize`:@@tpl.random-hobby.entry6:Guitar`, $localize`:@@tpl.random-hobby.entry7:Pottery`, $localize`:@@tpl.random-hobby.entry8:Birdwatching`,
    ],
    palette: {
      name: 'Workshop',
      colors: ['#0d9488', '#ea580c', '#7c3aed', '#16a34a', '#db2777', '#2563eb'],
    },
    centerText: $localize`:@@tpl.random-hobby.centerText:TRY`,
    centerColor: '#0d9488',
    winnerEffect: 'confetti',
    pointerType: 'diamond',
    spinDurationMs: 3500,
  },
  {
    id: 'bored',
    emoji: '🥱',
    tagline: $localize`:@@tpl.bored.tagline:Rainy days`,
    name: $localize`:@@tpl.bored.name:What to Do When Bored`,
    description: $localize`:@@tpl.bored.cardDesc:Nothing to do? Spin and do the first thing the wheel says.`,
    names: [
      $localize`:@@tpl.bored.entry1:Read a chapter`, $localize`:@@tpl.bored.entry2:Go for a walk`, $localize`:@@tpl.bored.entry3:Call a friend`, $localize`:@@tpl.bored.entry4:Tidy one drawer`,
      $localize`:@@tpl.bored.entry5:Learn a card trick`, $localize`:@@tpl.bored.entry6:Bake something`, $localize`:@@tpl.bored.entry7:Draw for 10 minutes`, $localize`:@@tpl.bored.entry8:Blanket fort`,
    ],
    palette: {
      name: 'Rainy Day',
      colors: ['#0ea5e9', '#6366f1', '#14b8a6', '#8b5cf6', '#06b6d4', '#3b82f6'],
    },
    centerText: $localize`:@@tpl.bored.centerText:GO`,
    centerColor: '#0ea5e9',
    winnerEffect: 'cartoon-fire',
    pointerType: 'bolt',
    spinDurationMs: 3000,
  },
  {
    id: 'self-care',
    emoji: '🌿',
    tagline: $localize`:@@tpl.self-care.tagline:Wellbeing`,
    name: $localize`:@@tpl.self-care.name:Self-Care Wheel`,
    description: $localize`:@@tpl.self-care.cardDesc:Small things that help: spin for one kind thing to do for yourself today.`,
    names: [
      $localize`:@@tpl.self-care.entry1:Drink some water`, $localize`:@@tpl.self-care.entry2:5-minute stretch`, $localize`:@@tpl.self-care.entry3:Walk outside`, $localize`:@@tpl.self-care.entry4:Text a friend`,
      $localize`:@@tpl.self-care.entry5:Read for 20 minutes`, $localize`:@@tpl.self-care.entry6:Take a long shower`, $localize`:@@tpl.self-care.entry7:An hour offline`, $localize`:@@tpl.self-care.entry8:Go to bed early`,
    ],
    palette: {
      name: 'Sage',
      colors: ['#84cc16', '#65a30d', '#a3e635', '#4d7c0f', '#bef264', '#3f6212'],
    },
    centerText: $localize`:@@tpl.self-care.centerText:BREATHE`,
    centerColor: '#65a30d',
    winnerEffect: 'applause',
    pointerType: 'drop',
    spinDurationMs: 4000,
  },
  {
    id: 'what-to-cook',
    emoji: '🍳',
    tagline: $localize`:@@tpl.what-to-cook.tagline:Home cooking`,
    name: $localize`:@@tpl.what-to-cook.name:What to Cook`,
    description: $localize`:@@tpl.what-to-cook.cardDesc:Staring into the fridge? Spin for tonight’s dish and start cooking.`,
    names: [
      $localize`:@@tpl.what-to-cook.entry1:Risotto`, $localize`:@@tpl.what-to-cook.entry2:Stir-fry`, $localize`:@@tpl.what-to-cook.entry3:Omelette`, $localize`:@@tpl.what-to-cook.entry4:Curry`,
      $localize`:@@tpl.what-to-cook.entry5:Homemade pizza`, $localize`:@@tpl.what-to-cook.entry6:Soup`, $localize`:@@tpl.what-to-cook.entry7:Tacos`, $localize`:@@tpl.what-to-cook.entry8:Pasta bake`,
    ],
    palette: {
      name: 'Kitchen',
      colors: ['#dc2626', '#f59e0b', '#16a34a', '#ea580c', '#ca8a04', '#b91c1c'],
    },
    centerText: $localize`:@@tpl.what-to-cook.centerText:COOK`,
    centerColor: '#dc2626',
    winnerEffect: 'cartoon-fire',
    pointerType: 'drop',
    spinDurationMs: 3000,
  },
  {
    id: 'superpower',
    emoji: '🦸',
    tagline: $localize`:@@tpl.superpower.tagline:Kids & storytelling`,
    name: $localize`:@@tpl.superpower.name:Random Superpower`,
    description: $localize`:@@tpl.superpower.cardDesc:If you could have one power… spin to find out which one you get.`,
    names: [
      $localize`:@@tpl.superpower.entry1:Flight`, $localize`:@@tpl.superpower.entry2:Invisibility`, $localize`:@@tpl.superpower.entry3:Teleportation`, $localize`:@@tpl.superpower.entry4:Super strength`,
      $localize`:@@tpl.superpower.entry5:Time travel`, $localize`:@@tpl.superpower.entry6:Mind reading`, $localize`:@@tpl.superpower.entry7:Talking to animals`, $localize`:@@tpl.superpower.entry8:Breathing underwater`,
    ],
    palette: {
      name: 'Comic Book',
      colors: ['#dc2626', '#2563eb', '#facc15', '#7c3aed', '#16a34a', '#f97316'],
    },
    centerText: $localize`:@@tpl.superpower.centerText:POWER`,
    centerColor: '#facc15',
    winnerEffect: 'fireworks',
    pointerType: 'bolt',
    spinDurationMs: 4000,
  },
  {
    id: 'charades',
    emoji: '🎭',
    tagline: $localize`:@@tpl.charades.tagline:Game night`,
    name: $localize`:@@tpl.charades.name:Charades Ideas`,
    description: $localize`:@@tpl.charades.cardDesc:Spin for something to act out — no words, no sounds, just gestures.`,
    names: [
      $localize`:@@tpl.charades.entry1:Brushing your teeth`, $localize`:@@tpl.charades.entry2:Surfing`, $localize`:@@tpl.charades.entry3:A T-rex`, $localize`:@@tpl.charades.entry4:Changing a tyre`,
      $localize`:@@tpl.charades.entry5:Walking a dog`, $localize`:@@tpl.charades.entry6:Making pizza`, $localize`:@@tpl.charades.entry7:A dancing robot`, $localize`:@@tpl.charades.entry8:Climbing a mountain`,
    ],
    palette: {
      name: 'Theatre',
      colors: ['#7f1d1d', '#b91c1c', '#ca8a04', '#991b1b', '#a16207', '#dc2626'],
    },
    centerText: $localize`:@@tpl.charades.centerText:ACT`,
    centerColor: '#ca8a04',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3500,
  },
  {
    id: 'random-job',
    emoji: '🧑‍🚀',
    tagline: $localize`:@@tpl.random-job.tagline:Games & careers`,
    name: $localize`:@@tpl.random-job.name:Random Job`,
    description: $localize`:@@tpl.random-job.cardDesc:A random job for role-play, stories, career days and guessing games.`,
    names: [
      $localize`:@@tpl.random-job.entry1:Astronaut`, $localize`:@@tpl.random-job.entry2:Chef`, $localize`:@@tpl.random-job.entry3:Detective`, $localize`:@@tpl.random-job.entry4:Firefighter`,
      $localize`:@@tpl.random-job.entry5:Pilot`, $localize`:@@tpl.random-job.entry6:Vet`, $localize`:@@tpl.random-job.entry7:Architect`, $localize`:@@tpl.random-job.entry8:Marine biologist`,
    ],
    palette: {
      name: 'Uniforms',
      colors: ['#1e40af', '#b45309', '#374151', '#b91c1c', '#0369a1', '#15803d'],
    },
    centerText: $localize`:@@tpl.random-job.centerText:JOB`,
    centerColor: '#1e40af',
    winnerEffect: 'confetti',
    pointerType: 'arrow',
    spinDurationMs: 3500,
  },
  {
    id: 'writing-prompts',
    emoji: '📝',
    tagline: $localize`:@@tpl.writing-prompts.tagline:Writers & classrooms`,
    name: $localize`:@@tpl.writing-prompts.name:Writing Prompts`,
    description: $localize`:@@tpl.writing-prompts.cardDesc:Spin for a story starter and write the first line before you can overthink it.`,
    names: [
      $localize`:@@tpl.writing-prompts.entry1:A letter never sent`, $localize`:@@tpl.writing-prompts.entry2:Last day on Earth`, $localize`:@@tpl.writing-prompts.entry3:A mysterious door`, $localize`:@@tpl.writing-prompts.entry4:The villain’s story`,
      $localize`:@@tpl.writing-prompts.entry5:Message in a bottle`, $localize`:@@tpl.writing-prompts.entry6:100 years later`, $localize`:@@tpl.writing-prompts.entry7:An odd inheritance`, $localize`:@@tpl.writing-prompts.entry8:The great storm`,
    ],
    palette: {
      name: 'Ink',
      colors: ['#1e293b', '#7c2d12', '#334155', '#78350f', '#0f172a', '#57534e'],
    },
    centerText: $localize`:@@tpl.writing-prompts.centerText:WRITE`,
    centerColor: '#fef3c7',
    winnerEffect: 'confetti',
    pointerType: 'drop',
    spinDurationMs: 3500,
  },
  {
    id: 'what-to-wear',
    emoji: '👗',
    tagline: $localize`:@@tpl.what-to-wear.tagline:Outfit challenges`,
    name: $localize`:@@tpl.what-to-wear.name:What to Wear`,
    description: $localize`:@@tpl.what-to-wear.cardDesc:Can’t decide on an outfit? Spin for today’s style challenge.`,
    names: [
      $localize`:@@tpl.what-to-wear.entry1:Something red`, $localize`:@@tpl.what-to-wear.entry2:All black`, $localize`:@@tpl.what-to-wear.entry3:Comfiest outfit`, $localize`:@@tpl.what-to-wear.entry4:Something forgotten`,
      $localize`:@@tpl.what-to-wear.entry5:Dress up for fun`, $localize`:@@tpl.what-to-wear.entry6:Stripes`, $localize`:@@tpl.what-to-wear.entry7:Denim on denim`, $localize`:@@tpl.what-to-wear.entry8:Monochrome`,
    ],
    palette: {
      name: 'Wardrobe',
      colors: ['#be185d', '#0f172a', '#a16207', '#1d4ed8', '#9d174d', '#6b7280'],
    },
    centerText: $localize`:@@tpl.what-to-wear.centerText:WEAR`,
    centerColor: '#be185d',
    winnerEffect: 'applause',
    pointerType: 'diamond',
    spinDurationMs: 3000,
  },
  {
    id: 'what-game-to-play',
    emoji: '🎮',
    tagline: $localize`:@@tpl.what-game-to-play.tagline:Gamers & streamers`,
    name: $localize`:@@tpl.what-game-to-play.name:What Game to Play`,
    description: $localize`:@@tpl.what-game-to-play.cardDesc:Too many games, not enough decisions: spin for tonight’s genre.`,
    names: [
      $localize`:@@tpl.what-game-to-play.entry1:Racing`, $localize`:@@tpl.what-game-to-play.entry2:Puzzle`, $localize`:@@tpl.what-game-to-play.entry3:Platformer`, $localize`:@@tpl.what-game-to-play.entry4:Strategy`,
      $localize`:@@tpl.what-game-to-play.entry5:Horror`, $localize`:@@tpl.what-game-to-play.entry6:RPG`, $localize`:@@tpl.what-game-to-play.entry7:Co-op`, $localize`:@@tpl.what-game-to-play.entry8:Sports`,
    ],
    palette: {
      name: 'Neon',
      colors: ['#a855f7', '#22d3ee', '#f43f5e', '#84cc16', '#6366f1', '#f59e0b'],
    },
    centerText: $localize`:@@tpl.what-game-to-play.centerText:PLAY`,
    centerColor: '#a855f7',
    winnerEffect: 'fireworks',
    pointerType: 'bolt',
    spinDurationMs: 4000,
  },
  {
    id: 'heads-or-tails',
    emoji: '🪙',
    tagline: $localize`:@@tpl.heads-or-tails.tagline:Coin toss`,
    name: $localize`:@@tpl.heads-or-tails.name:Heads or Tails`,
    description: $localize`:@@tpl.heads-or-tails.cardDesc:A coin toss on a wheel: two sides, one spin, no coin needed.`,
    names: [
      $localize`:@@tpl.heads-or-tails.entry1:Heads`, $localize`:@@tpl.heads-or-tails.entry2:Tails`, $localize`:@@tpl.heads-or-tails.entry1:Heads`, $localize`:@@tpl.heads-or-tails.entry2:Tails`, $localize`:@@tpl.heads-or-tails.entry1:Heads`, $localize`:@@tpl.heads-or-tails.entry2:Tails`,
    ],
    palette: {
      name: 'Coin',
      // Three slices each, alternating: still exactly fifty-fifty, and labels big enough to read.
      colors: ['#ca8a04', '#78716c'],
    },
    centerText: $localize`:@@tpl.heads-or-tails.centerText:FLIP`,
    centerColor: '#ca8a04',
    winnerEffect: 'confetti',
    pointerType: 'arrow',
    spinDurationMs: 3000,
  },
  {
    id: 'punishment',
    emoji: '😈',
    tagline: $localize`:@@tpl.punishment.tagline:Forfeits & streams`,
    name: $localize`:@@tpl.punishment.name:Punishment Wheel`,
    description: $localize`:@@tpl.punishment.cardDesc:Lost the round? Spin for a harmless forfeit and take it like a sport.`,
    names: [
      $localize`:@@tpl.punishment.entry1:Sing a song`, $localize`:@@tpl.punishment.entry2:Dance for 30 seconds`, $localize`:@@tpl.punishment.entry3:Embarrassing story`, $localize`:@@tpl.punishment.entry4:30-second plank`,
      $localize`:@@tpl.punishment.entry5:Talk in an accent`, $localize`:@@tpl.punishment.entry6:Compliment everyone`, $localize`:@@tpl.punishment.entry7:Animal impression`, $localize`:@@tpl.punishment.entry8:Talk in rhyme`,
    ],
    palette: {
      name: 'Devilish',
      colors: ['#991b1b', '#dc2626', '#7f1d1d', '#ef4444', '#450a0a', '#f87171'],
    },
    centerText: $localize`:@@tpl.punishment.centerText:OOPS`,
    centerColor: '#991b1b',
    winnerEffect: 'fire',
    pointerType: 'bolt',
    spinDurationMs: 4500,
  },
  {
    id: 'music-genre',
    emoji: '🎵',
    tagline: $localize`:@@tpl.music-genre.tagline:Playlists & parties`,
    name: $localize`:@@tpl.music-genre.name:Random Music Genre`,
    description: $localize`:@@tpl.music-genre.cardDesc:Spin for a genre and build tonight’s playlist around it.`,
    names: [
      $localize`:@@tpl.music-genre.entry1:Rock`, $localize`:@@tpl.music-genre.entry2:Jazz`, $localize`:@@tpl.music-genre.entry3:Hip hop`, $localize`:@@tpl.music-genre.entry4:Classical`,
      $localize`:@@tpl.music-genre.entry5:Reggae`, $localize`:@@tpl.music-genre.entry6:Electronic`, $localize`:@@tpl.music-genre.entry7:Country`, $localize`:@@tpl.music-genre.entry8:Latin`,
    ],
    palette: {
      name: 'Vinyl',
      colors: ['#111827', '#db2777', '#1f2937', '#7c3aed', '#0f172a', '#0891b2'],
    },
    centerText: $localize`:@@tpl.music-genre.centerText:MUSIC`,
    centerColor: '#db2777',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 3500,
  },
  {
    id: 'halloween-costume',
    emoji: '🎃',
    tagline: $localize`:@@tpl.halloween-costume.tagline:Halloween`,
    name: $localize`:@@tpl.halloween-costume.name:Halloween Costume`,
    description: $localize`:@@tpl.halloween-costume.cardDesc:No costume yet? Spin and dress as whatever the wheel picks.`,
    names: [
      $localize`:@@tpl.halloween-costume.entry1:Vampire`, $localize`:@@tpl.halloween-costume.entry2:Witch`, $localize`:@@tpl.halloween-costume.entry3:Ghost`, $localize`:@@tpl.halloween-costume.entry4:Zombie`,
      $localize`:@@tpl.halloween-costume.entry5:Skeleton`, $localize`:@@tpl.halloween-costume.entry6:Pirate`, $localize`:@@tpl.halloween-costume.entry7:Mummy`, $localize`:@@tpl.halloween-costume.entry8:Werewolf`,
    ],
    palette: {
      name: 'Pumpkin',
      colors: ['#ea580c', '#1c1917', '#7c3aed', '#f97316', '#292524', '#65a30d'],
    },
    centerText: $localize`:@@tpl.halloween-costume.centerText:BOO`,
    centerColor: '#ea580c',
    winnerEffect: 'fire',
    pointerType: 'drop',
    spinDurationMs: 4000,
  },
];
