import { WheelTemplateDefinition } from '../../services/wheel-configurator.models';

export interface WheelTemplateItem extends WheelTemplateDefinition {
  id: string;
  emoji: string;
  tagline: string;
}

export const WHEEL_TEMPLATES: WheelTemplateItem[] = [
  {
    id: 'yes-or-no',
    emoji: '✅',
    tagline: 'Instant decisions',
    name: 'Yes or No',
    description: 'A quick decision maker: let the wheel answer for you.',
    names: ['Yes', 'No', 'Yes', 'No', 'Yes', 'No'],
    palette: { name: 'Yes or No', colors: ['#10B981', '#EF4444'] },
    centerText: 'PICK',
    centerColor: '#0f172a',
    winnerEffect: 'confetti',
    pointerType: 'arrow',
    spinDurationMs: 3000,
  },
  {
    id: 'prize-giveaway',
    emoji: '🎁',
    tagline: 'Giveaways & contests',
    name: 'Prize Giveaway',
    description: 'A ready-made prize wheel for giveaways, streams, and events.',
    names: [
      '€50 Gift Card',
      'Free T-Shirt',
      'Sticker Pack',
      'Mystery Box',
      '20% Discount',
      'Free Shipping',
      'Try Again',
      'Grand Prize',
    ],
    palette: {
      name: 'Prize Gold',
      colors: ['#F59E0B', '#B45309', '#FBBF24', '#78350F', '#FDE68A', '#92400E'],
    },
    centerText: 'WIN',
    centerColor: '#F59E0B',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 5000,
  },
  {
    id: 'whats-for-dinner',
    emoji: '🍕',
    tagline: 'Food roulette',
    name: "What's for Dinner?",
    description: 'Nobody can decide? Spin and dinner is served.',
    names: ['Pizza', 'Sushi', 'Burger', 'Pasta', 'Tacos', 'Salad', 'Ramen', 'BBQ'],
    palette: {
      name: 'Dinner Warm',
      colors: ['#f43f5e', '#fb923c', '#fbbf24', '#84cc16', '#f97316', '#dc2626'],
    },
    centerText: 'EAT',
    centerColor: '#fb923c',
    winnerEffect: 'cartoon-fire',
    pointerType: 'drop',
    spinDurationMs: 3000,
  },
  {
    id: 'team-picker',
    emoji: '👥',
    tagline: 'Standups & classrooms',
    name: 'Team Picker',
    description: 'Pick who speaks next, who presents, or who buys coffee.',
    names: ['Alex', 'Sam', 'Charlie', 'Jordan', 'Taylor', 'Riley', 'Morgan', 'Casey'],
    palette: {
      name: 'Team Cool',
      colors: ['#3B82F6', '#06B6D4', '#8B5CF6', '#0EA5E9', '#6366F1', '#14B8A6'],
    },
    centerText: 'PICK',
    centerColor: '#3B82F6',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3000,
  },
  {
    id: 'truth-or-dare',
    emoji: '🎭',
    tagline: 'Party games',
    name: 'Truth or Dare',
    description: 'The party classic: let the wheel raise the stakes.',
    names: ['Truth', 'Dare', 'Truth', 'Dare', 'Truth', 'Dare', 'Truth', 'Dare'],
    palette: { name: 'Truth or Dare', colors: ['#A855F7', '#EC4899'] },
    centerText: 'DARE',
    centerColor: '#A855F7',
    winnerEffect: 'confetti',
    pointerType: 'bolt',
    spinDurationMs: 3000,
  },
  {
    id: 'discount-wheel',
    emoji: '🏷️',
    tagline: 'Shops & promos',
    name: 'Discount Wheel',
    description: 'Spin-to-win promo wheel for shops, fairs, and landing pages.',
    names: [
      '5% Off',
      '10% Off',
      '15% Off',
      '20% Off',
      '30% Off',
      '50% Off',
      'Free Gift',
      'No Luck',
    ],
    palette: {
      name: 'Promo Pop',
      colors: ['#EF4444', '#F59E0B', '#10B981', '#3B82F6', '#A855F7', '#EC4899'],
    },
    centerText: 'SPIN',
    centerColor: '#EF4444',
    winnerEffect: 'fireworks',
    pointerType: 'diamond',
    spinDurationMs: 4000,
  },
  {
    id: 'movie-night',
    emoji: '🎬',
    tagline: 'Movie night',
    name: 'Movie Night',
    description: 'Pick tonight’s genre and stop scrolling the catalog.',
    names: [
      'Action',
      'Comedy',
      'Horror',
      'Sci-Fi',
      'Romance',
      'Thriller',
      'Animation',
      'Documentary',
    ],
    palette: {
      name: 'Cinema Noir',
      colors: ['#0f172a', '#7c3aed', '#1e293b', '#f43f5e', '#334155', '#f59e0b'],
    },
    centerText: 'PLAY',
    centerColor: '#7c3aed',
    winnerEffect: 'confetti',
    pointerType: 'drop',
    spinDurationMs: 3000,
  },
  {
    id: 'workout-spinner',
    emoji: '💪',
    tagline: 'Fitness',
    name: 'Workout Spinner',
    description: 'Random mini-workouts: spin and do what the wheel says.',
    names: [
      '10 Push-ups',
      '20 Squats',
      '30s Plank',
      '15 Burpees',
      '20 Jumping Jacks',
      '10 Lunges',
      '30s Wall Sit',
      'Rest 1 min',
    ],
    palette: {
      name: 'Energy',
      colors: ['#22c55e', '#16a34a', '#84cc16', '#15803d', '#a3e635', '#4d7c0f'],
    },
    centerText: 'GO!',
    centerColor: '#22c55e',
    winnerEffect: 'fire',
    pointerType: 'bolt',
    spinDurationMs: 3000,
  },
  {
    id: 'lucky-numbers',
    emoji: '🎱',
    tagline: 'Raffles & lotteries',
    name: 'Lucky Numbers',
    description: 'Numbers 1 to 12 for raffles, tombola, and quick draws.',
    names: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    palette: {
      name: 'Neon Numbers',
      colors: ['#39FF14', '#FF00FF', '#00FFFF', '#FFFF00', '#FF5F1F', '#4D4DFF'],
    },
    centerText: 'LUCK',
    centerColor: '#00FFFF',
    winnerEffect: 'fireworks',
    pointerType: 'star',
    spinDurationMs: 5000,
  },
  {
    id: 'icebreaker-questions',
    emoji: '🧊',
    tagline: 'Meetings & meetups',
    name: 'Icebreaker Questions',
    description: 'Warm up any group: spin for a random get-to-know-you question.',
    names: [
      'Dream vacation?',
      'Hidden talent?',
      'Favorite food?',
      'Best concert ever?',
      'Pick a superpower',
      'First job story',
      'Karaoke go-to song',
      'Weirdest habit?',
    ],
    palette: {
      name: 'Icebreaker',
      colors: ['#0891b2', '#38bdf8', '#0e7490', '#7dd3fc', '#0369a1', '#bae6fd'],
    },
    centerText: 'ASK',
    centerColor: '#38bdf8',
    winnerEffect: 'applause',
    pointerType: 'finger',
    spinDurationMs: 3000,
  },
];
